GET http://localhost:9999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDk2OTcyMDcsImV4cCI6MTcwOTcwNDQwNywiYXVkIjoiNjVlNzQwZTA4OWQyNzI0ZTIwZGE2MTJmIiwiaXNzIjoibG9jYWxob3N0Ojk5OTkifQ.RahtAfBRSAiRh1ecJnTKoIAKrbwNg1OQir6MSbCHr10

###
GET http://localhost:9999/abc-xyz

###
POST http://localhost:9999/auth/register
Content-Type: application/json

{
    "email": "thopn3@fpt.edu.vn",
    "password": "123"
}

###
POST http://localhost:9999/auth/login
Content-Type: application/json

{
    "email": "thopn3@fpt.edu.vn",
    "password": "123"
}

###
POST http://localhost:9999/auth/refresh-token

###
DELETE  http://localhost:9999/auth/logout
